#https://www.google.com/search?q=weather+raebareli&rlz=1C1CHBF_enIN1079IN1080&oq=weathert+raebare&gs_lcrp=EgZjaHJvbWUqDwgBEAAYDRiDARixAxiABDIGCAAQRRg5Mg8IARAAGA0YgwEYsQMYgAQyCQgCEAAYDRiABDIJCAMQABgNGIAEMgkIBBAAGA0YgAQyCQgFEAAYDRiABDIJCAYQABgNGIAEMgkIBxAAGA0YgAQyCQgIEAAYDRiABDIJCAkQABgNGIAE0gEIODI5OWowajeoAgiwAgHxBZiPDLlDpHCj8QWYjwy5Q6Rwow&sourceid=chrome&ie=UTF-8

from requests_html import HTMLSession
import speech_to_text

s=HTMLSession()
url=f'https://www.google.com/search?q=weather+raebareli&rlz=1C1CHBF_enIN1079IN1080&oq=weathert+raebare&gs_lcrp=EgZjaHJvbWUqDwgBEAAYDRiDARixAxiABDIGCAAQRRg5Mg8IARAAGA0YgwEYsQMYgAQyCQgCEAAYDRiABDIJCAMQABgNGIAEMgkIBBAAGA0YgAQyCQgFEAAYDRiABDIJCAYQABgNGIAEMgkIBxAAGA0YgAQyCQgIEAAYDRiABDIJCAkQABgNGIAE0gEIODI5OWowajeoAgiwAgHxBZiPDLlDpHCj8QWYjwy5Q6Rwow&sourceid=chrome&ie=UTF-8'
